# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Portview < Formula
  desc "Lightweight web-based port monitor"
  homepage "https://github.com/vcdim/portview"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/vcdim/portview/releases/download/v0.3.0/portview_0.3.0_darwin_amd64.tar.gz"
      sha256 "d2c9ba274a278a8011a751831f0def6243d655fd718b79244d92a1518ca3cfdd"

      define_method(:install) do
        bin.install "portview"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/vcdim/portview/releases/download/v0.3.0/portview_0.3.0_darwin_arm64.tar.gz"
      sha256 "3feec46d4022566293bf9602578cc6be6e7149bfc602b97471340b0b39e1aeeb"

      define_method(:install) do
        bin.install "portview"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/vcdim/portview/releases/download/v0.3.0/portview_0.3.0_linux_amd64.tar.gz"
      sha256 "fac58431bbce5473ec16f2dbcb7bfafed594ef12426ce07b16d31ed7faa03f74"
      define_method(:install) do
        bin.install "portview"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/vcdim/portview/releases/download/v0.3.0/portview_0.3.0_linux_arm64.tar.gz"
      sha256 "99f06a46873d6fb32a6bd797630d8cc48bd03b8f858bf49721ead3fb2df0aa20"
      define_method(:install) do
        bin.install "portview"
      end
    end
  end
end
