# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Webtop < Formula
  desc "Lightweight web-based system dashboard"
  homepage "https://github.com/vcdim/webtop"
  version "0.4.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/vcdim/webtop/releases/download/v0.4.0/webtop_0.4.0_darwin_amd64.tar.gz"
      sha256 "b3b9acdbf45bb3fb3d3fc9c0b9773b5a2345f72d2973e410afc65c9aca022c64"

      define_method(:install) do
        bin.install "webtop"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/vcdim/webtop/releases/download/v0.4.0/webtop_0.4.0_darwin_arm64.tar.gz"
      sha256 "92dbed05b5fce96b8aea31ce2e6a588990e960264e8c263c445b2075bd53bad7"

      define_method(:install) do
        bin.install "webtop"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/vcdim/webtop/releases/download/v0.4.0/webtop_0.4.0_linux_amd64.tar.gz"
      sha256 "08475c9e10b7dea10a9b697a78f4c38d1c51dce936f2d3901de48073e8875e1a"
      define_method(:install) do
        bin.install "webtop"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/vcdim/webtop/releases/download/v0.4.0/webtop_0.4.0_linux_arm64.tar.gz"
      sha256 "c975fb6a3b69d386dd11194fbd941805385960ec7e1cbc5d8ecef17fb66190e5"
      define_method(:install) do
        bin.install "webtop"
      end
    end
  end
end
