# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Webtop < Formula
  desc "Lightweight web-based system dashboard"
  homepage "https://github.com/vcdim/webtop"
  version "0.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/vcdim/webtop/releases/download/v0.0.1/webtop_0.0.1_darwin_amd64.tar.gz"
      sha256 "e7c9d1b3fce26e52d909ed5bc70d20f1010fa8b169c48e22b8095a5188f7f9bd"

      define_method(:install) do
        bin.install "webtop"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/vcdim/webtop/releases/download/v0.0.1/webtop_0.0.1_darwin_arm64.tar.gz"
      sha256 "a043fcf23ee9b4e68a92a1ac782ef0698b835e35946419d8e484ce03d32ee192"

      define_method(:install) do
        bin.install "webtop"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/vcdim/webtop/releases/download/v0.0.1/webtop_0.0.1_linux_amd64.tar.gz"
      sha256 "4eb4e1bc2d0a296c229a3bed0d7192e16f1861a6cace7698ecf011c642f7038d"
      define_method(:install) do
        bin.install "webtop"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/vcdim/webtop/releases/download/v0.0.1/webtop_0.0.1_linux_arm64.tar.gz"
      sha256 "687f49736033828abc3fd89551d0c093f0f1f0643d9d6d0ddf6f00bf1a2f83b2"
      define_method(:install) do
        bin.install "webtop"
      end
    end
  end
end
