# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Webtop < Formula
  desc "Lightweight web-based system dashboard"
  homepage "https://github.com/vcdim/webtop"
  version "0.4.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/vcdim/webtop/releases/download/v0.4.1/webtop_0.4.1_darwin_amd64.tar.gz"
      sha256 "bc61aa37fcc7b0794c70679692d0df97271307688c1ec56d8eb1cfb1988c93cd"

      define_method(:install) do
        bin.install "webtop"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/vcdim/webtop/releases/download/v0.4.1/webtop_0.4.1_darwin_arm64.tar.gz"
      sha256 "d824583c1844044f2fbbfdaed76ae9ed633e364e00678ef8364c3c2b9d50f336"

      define_method(:install) do
        bin.install "webtop"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/vcdim/webtop/releases/download/v0.4.1/webtop_0.4.1_linux_amd64.tar.gz"
      sha256 "43496700d6a77f1e34bf3d2403dd5921db84fb84d81f3d6417d9cbee7d6f2689"
      define_method(:install) do
        bin.install "webtop"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/vcdim/webtop/releases/download/v0.4.1/webtop_0.4.1_linux_arm64.tar.gz"
      sha256 "cde33903bfe169f19677583aee433676397e5dd3f2bdfdd3c8673a74d070080a"
      define_method(:install) do
        bin.install "webtop"
      end
    end
  end
end
